services:
  db:
    image: postgres:15-alpine
    container_name: edumarket-db-1
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - edumarket_pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    container_name: edumarket-backend-1
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@edumarket-db-1:5432/${DB_NAME}
    ports:
      - "8000:8000"
    volumes:
      - ./backend/static:/app/static
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: edumarket-frontend-1
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://87.232.127.125
    depends_on:
      - backend

volumes:
  edumarket_pgdata:
